---
swagger: "2.0"
info:
  version: "Swagger 2.0"
  title: "https://ppsapi-dev01.api.psiq-int-dev.aws.cloud.lfg.com"
basePath: ""
paths:
  /ppsapi/get_agent:
    post:
      operationId: "Get Agent"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Request body"
          required: true
          schema:
            type: "object"
            properties:
              agent_id:
                type: "string"
                description: "ID of the agent to retrieve"
              agent_profile:
                type: "string"
                description: "Profile of the agent"
              calling_app:
                type: "string"
                description: "The application making the call"
            required:
              - agent_id
              - agent_profile
              - calling_app
          examples:
            application/json:
              { agent_id: "12345", agent_profile: "001", calling_app: "my_app" }
      responses:
        "200":
          description: "Successful response"
          schema:
            type: "object"
            properties:
              agent_id:
                type: "string"
              agent_profile:
                type: "string"
              sas_office_number:
                type: "string"
              hierarchy_level:
                type: "number"
              first_name:
                type: "string"
              last_name:
                type: "string"
              coporate_name:
                type: "string"
              master_agent_id:
                type: "string"
              national_prod_no:
                type: "string"
              crd_number:
                type: "string"
          examples:
            application/json:
              agent_id: "12345"
              agent_profile: "001"
              sas_office_number: "TE001S"
              hierarchy_level: 1
              first_name: "John"
              last_name: "Doe"
              coporate_name: "Acme Corp"
              master_agent_id: "54321"
              national_prod_no: "2020202"
              crd_number: "CRD78910"
        "401":
          description: "Unauthorized"
        "415":
          description: "Unsupported Media Type"
  /ppsapi/actuator/health:
    get:
      operationId: "Health Check"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Service is healthy"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
          examples:
            application/json: { status: "ok" }
